// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tozastation/go_grpc_layered_arch_example/internal/grpc/rpc/user/generated.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Base Model
type ReadUser struct {
	// UUID
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUser) Reset()         { *m = ReadUser{} }
func (m *ReadUser) String() string { return proto.CompactTextString(m) }
func (*ReadUser) ProtoMessage()    {}
func (*ReadUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac4fce9a85e27976, []int{0}
}

func (m *ReadUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUser.Unmarshal(m, b)
}
func (m *ReadUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUser.Marshal(b, m, deterministic)
}
func (m *ReadUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUser.Merge(m, src)
}
func (m *ReadUser) XXX_Size() int {
	return xxx_messageInfo_ReadUser.Size(m)
}
func (m *ReadUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUser.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUser proto.InternalMessageInfo

func (m *ReadUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type WriteUser struct {
	// UUID
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteUser) Reset()         { *m = WriteUser{} }
func (m *WriteUser) String() string { return proto.CompactTextString(m) }
func (*WriteUser) ProtoMessage()    {}
func (*WriteUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac4fce9a85e27976, []int{1}
}

func (m *WriteUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteUser.Unmarshal(m, b)
}
func (m *WriteUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteUser.Marshal(b, m, deterministic)
}
func (m *WriteUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteUser.Merge(m, src)
}
func (m *WriteUser) XXX_Size() int {
	return xxx_messageInfo_WriteUser.Size(m)
}
func (m *WriteUser) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteUser.DiscardUnknown(m)
}

var xxx_messageInfo_WriteUser proto.InternalMessageInfo

func (m *WriteUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WriteUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WriteUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *WriteUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Req, Resp
// Read Usecase
type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac4fce9a85e27976, []int{2}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	User                 *ReadUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac4fce9a85e27976, []int{3}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetUser() *ReadUser {
	if m != nil {
		return m.User
	}
	return nil
}

// Create Usecase
type CreateRequest struct {
	User                 *WriteUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac4fce9a85e27976, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUser() *WriteUser {
	if m != nil {
		return m.User
	}
	return nil
}

// Login Usecase
type LoginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac4fce9a85e27976, []int{5}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type LoginResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac4fce9a85e27976, []int{6}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReadUser)(nil), "user.ReadUser")
	proto.RegisterType((*WriteUser)(nil), "user.WriteUser")
	proto.RegisterType((*ReadRequest)(nil), "user.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "user.ReadResponse")
	proto.RegisterType((*CreateRequest)(nil), "user.CreateRequest")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
}

func init() {
	proto.RegisterFile("github.com/tozastation/go_grpc_layered_arch_example/internal/grpc/rpc/user/generated.proto", fileDescriptor_ac4fce9a85e27976)
}

var fileDescriptor_ac4fce9a85e27976 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4f, 0xeb, 0xd3, 0x40,
	0x10, 0xfd, 0xb5, 0xc6, 0xda, 0x4e, 0xff, 0xe1, 0x16, 0x24, 0x44, 0x04, 0x59, 0x2f, 0x9e, 0xb2,
	0x10, 0x05, 0xef, 0x8a, 0x20, 0xd2, 0x53, 0x44, 0x84, 0x5e, 0xc2, 0x36, 0x3b, 0xa6, 0x0b, 0x49,
	0x36, 0xee, 0x6e, 0xd4, 0xfa, 0x95, 0xfc, 0x92, 0xb2, 0xbb, 0x49, 0x6d, 0xbd, 0xfa, 0x3b, 0x04,
	0x32, 0x6f, 0xde, 0x9b, 0xf7, 0x26, 0x13, 0x38, 0x54, 0xd2, 0x9e, 0xfa, 0x63, 0x5a, 0xaa, 0x86,
	0x59, 0xf5, 0x8b, 0x1b, 0xcb, 0xad, 0x54, 0x2d, 0xab, 0x54, 0x51, 0xe9, 0xae, 0x2c, 0x6a, 0x7e,
	0x46, 0x8d, 0xa2, 0xe0, 0xba, 0x3c, 0x15, 0xf8, 0x93, 0x37, 0x5d, 0x8d, 0x4c, 0xb6, 0x16, 0x75,
	0xcb, 0x6b, 0xe6, 0x28, 0xcc, 0x3d, 0xbd, 0x41, 0xcd, 0x2a, 0x6c, 0x51, 0x73, 0x8b, 0x22, 0xed,
	0xb4, 0xb2, 0x8a, 0x44, 0x0e, 0x4d, 0x9e, 0x56, 0x4a, 0x55, 0x35, 0x32, 0x8f, 0x1d, 0xfb, 0xaf,
	0x0c, 0x9b, 0xce, 0x9e, 0x03, 0x85, 0x7e, 0x80, 0x79, 0x8e, 0x5c, 0x7c, 0x36, 0xa8, 0xc9, 0x06,
	0xa6, 0x52, 0xc4, 0x93, 0xe7, 0x93, 0x97, 0x8b, 0x7c, 0x2a, 0x05, 0x21, 0x10, 0xb5, 0xbc, 0xc1,
	0x78, 0xea, 0x11, 0xff, 0x4e, 0x62, 0x78, 0xc4, 0x85, 0xd0, 0x68, 0x4c, 0xfc, 0xc0, 0xc3, 0x63,
	0x49, 0x11, 0x16, 0x5f, 0xb4, 0xb4, 0xf8, 0xff, 0xa3, 0x48, 0x02, 0xf3, 0x8e, 0x1b, 0xf3, 0x43,
	0x69, 0x11, 0x47, 0xbe, 0x75, 0xa9, 0xe9, 0x33, 0x58, 0xba, 0xc0, 0x39, 0x7e, 0xeb, 0xd1, 0xd8,
	0x7f, 0x8d, 0x68, 0x06, 0xab, 0xd0, 0x36, 0x9d, 0x6a, 0x0d, 0x12, 0x0a, 0xfe, 0x23, 0x78, 0xc6,
	0x32, 0xdb, 0xa4, 0xae, 0x48, 0xc7, 0x8d, 0x73, 0xdf, 0xa3, 0xaf, 0x61, 0xfd, 0x4e, 0x23, 0xb7,
	0x38, 0x0e, 0x7d, 0x71, 0x23, 0xda, 0x06, 0xd1, 0x65, 0xb9, 0x41, 0xb5, 0x81, 0xd5, 0x5e, 0x55,
	0xb2, 0x1d, 0x44, 0x74, 0x0b, 0xeb, 0xa1, 0x0e, 0xd6, 0xd9, 0xef, 0x09, 0x2c, 0x1d, 0xff, 0x13,
	0xea, 0xef, 0xb2, 0x44, 0xc2, 0x20, 0x72, 0xc6, 0xe4, 0xf1, 0xdf, 0x10, 0x83, 0x36, 0x21, 0xd7,
	0x50, 0x90, 0xd3, 0x3b, 0xf2, 0x06, 0x66, 0x21, 0x17, 0xd9, 0x85, 0xfe, 0x4d, 0xca, 0xe4, 0x49,
	0x1a, 0x0e, 0x9b, 0x8e, 0x87, 0x4d, 0xdf, 0xbb, 0xc3, 0xd2, 0x3b, 0x92, 0xc1, 0x43, 0x1f, 0x85,
	0x0c, 0x73, 0xaf, 0x73, 0x26, 0xbb, 0x1b, 0x6c, 0x34, 0x7b, 0xbb, 0x3f, 0x7c, 0xbc, 0xbf, 0x3f,
	0xf1, 0x38, 0xf3, 0x99, 0x5e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x61, 0xcd, 0xaf, 0xde,
	0x02, 0x00, 0x00,
}
